// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string Sheet1_mission bounty hunter which improve  your ranking, hard enough to make the enery bar empty or to need a better gun. = "mission bounty hunter which improve  your ranking, hard enough to make the enery bar empty or to need a better gun.";
        public static string Sheet1_poker game = "poker game";
        public static string Sheet1_premium emotions = "premium emotions";
        public static string Sheet1_Feedback = "Feedback";
        public static string Sheet1_Add sound effects to the HS, variation of skull crush sounds. = "Add sound effects to the HS, variation of skull crush sounds.";
        public static string Sheet1_When the player doesn't have any more energy and pressed the Steal button, show the amount of silver the other player has to motivate the player to buy guarana juice = "When the player doesn't have any more energy and pressed the Steal button, show the amount of silver the other player has to motivate the player to buy guarana juice";
        public static string Sheet1_Put damages in color by tranche, 1-100 white, 101-500 green, … to give the impression of power when reaching a new color = "Put damages in color by tranche, 1-100 white, 101-500 green, … to give the impression of power when reaching a new color";
        public static string Sheet1_Mini games with scores - can send the scores to your friend, playable once a day, can pay to play more of it. Get a reward of it = "Mini games with scores - can send the scores to your friend, playable once a day, can pay to play more of it. Get a reward of it";
        public static string Sheet1_Every time no more of a duel item, an item is displayed with a price in premium currency on it, clicking on it will buy and throw the item directly to the enemy. = "Every time no more of a duel item, an item is displayed with a price in premium currency on it, clicking on it will buy and throw the item directly to the enemy.";
        public static string Sheet1_Crafting System = "Crafting System";
        public static string Sheet1_Goal  = "Goal ";
        public static string Sheet1_Goal Reward = "Goal Reward";
        public static string Sheet1_Gun Craft = "Gun Craft";
        public static string Sheet1_Use Loot drop to craft the guns = "Use Loot drop to craft the guns";
        public static string Sheet1_Timer on Crafts = "Timer on Crafts";
        public static string Sheet1_Gun Upgrade = "Gun Upgrade";
        public static string Sheet1_Use Loot drop to upgrade the guns = "Use Loot drop to upgrade the guns";
        public static string Sheet1_Use HC to upgrade the gun fully = "Use HC to upgrade the gun fully";
        public static string Sheet1_Crafting items drop = "Crafting items drop";
        public static string Sheet1_If Perfect, increase loot drop chance = "If Perfect, increase loot drop chance";
        public static string Sheet1_If HS Kill, increase loot drop chance = "If HS Kill, increase loot drop chance";
        public static string Sheet1_Soft Boost % loot drop chance = "Soft Boost % loot drop chance";
        public static string Sheet1_Gatcha Gun = "Gatcha Gun";
        public static string Sheet1_HC to get a random Gun that can be crafted = "HC to get a random Gun that can be crafted";
        public static string Sheet1_SC to get a random Gun that can be crafted OR Energy OR .. = "SC to get a random Gun that can be crafted OR Energy OR ..";
    }
}